# Generated by Django 2.0.3 on 2018-08-29 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_faltas', models.IntegerField(default=0)),
                ('compromiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablero.Compromiso')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=2)),
                ('minuto', models.CharField(max_length=10)),
                ('numero_set', models.IntegerField()),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablero.Juego')),
            ],
        ),
    ]
